[package]
name = "quin"
version = "0.0.1"
edition = "2021"

[dependencies]
egui_backend = { version = "0.2.0" }
egui_window_glfw_passthrough = { version = "0.2.1" }
egui_render_wgpu = { version = "0.3.0" }
rdev = "0.5.2"
image = "0.24.6"
serde = { version = "1.0.160", features = ["derive"] }
toml = "0.7.3"
once_cell = "1.17.1"
linked-hash-map = "0.5.6"
