[package]
name = "quin"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13", features = ["dynamic_linking", "file_watcher"] }
bevy_egui = "0.26"
rdev = { version = "0.5.3", features = ["unstable_grab"] }
tray-icon = "0.13"
crossbeam = "0.8.4"
once_cell = "1.19.0"
image = "0.25"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
