[common]
active_handlers = [
    "grid-mode-handler",
    "mouse-buttons-emulation-handler",
    "precise-mode-handler"
]

#[handlers.grid-mode-handler]
#pivot_grid_density_px = 10
#[handlers.grid-mode-handler.bindings]
#gm_activate = "R(AltRight)"
#
#[handlers.mouse-buttons-emulation-handler]
#scroll_speed = 2
#[handlers.mouse-buttons-emulation-handler.bindings]
#mb_toggle = "R(AltRight)"
#mb_activate = "P(AltLeft)"
#mb_deactivate = "R(AltLeft)"
#mb_left = "P(SemiColon)"
#mb_right = "P(Quote)"
#mb_middle = "P(Slash)"
#mb_scroll_up = "P(KeyK)"
#mb_scroll_down = "P(KeyJ)"
#mb_scroll_left = "P(KeyH)"
#mb_scroll_right = "P(KeyL)"
#
#[handlers.precise-mode-handler]
#cursor_speed = 5
#[handlers.precise-mode-handler.bindings]
#pm_activate = "R(ControlRight)P(ShiftLeft)"
#pm_deactivate = "R(ShiftLeft)"
#pm_move_left = "P(KeyH)"
#pm_move_right = "P(KeyL)"
#pm_move_top = "P(KeyK)"
#pm_move_bottom = "P(KeyJ)"
#pm_drag_and_drop = "P(KeyV)"
