name: "QUIN Test reporting"
description: "Quin pipeline to collect test and code coverage reports"
emoji: ":codecov:"
color: "#245f78"
hook:
  branch-filter-pattern: "main"
steps:
  - command: "buildkite-agent pipeline upload ./.buildkite/test-pipeline.yml"
    label: ":git:"
