[package]
name = "sequence-to-event"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true }
# todo common crate should not depend on plugin crate
input-sequence-api = { workspace = true }
